# OpenRemote v3
#
# Profile for doing UI development work.
#
# Please see profile/deploy.yml for configuration details for each service.
#
volumes:
  manager-data:

services:
  keycloak:
    extends:
      file: deploy.yml
      service: keycloak
    #volumes:
    #   Map custom themes
    #  - ../deployment:/deployment
    # Access directly if needed on localhost
    ports:
      - "8081:8080"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HOSTNAME_PORT: ${KC_HOSTNAME_PORT:-8080}
      # Prevent theme caching during dev
      KEYCLOAK_START_OPTS: --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
  postgresql:
    extends:
      file: deploy.yml
      service: postgresql
    volumes:
      - manager-data:/storage
      - ../tmp/datapoint:/storage/datapoint
    # Access directly if needed on localhost
    ports:
      - "5432:5432"
  map:
    extends:
      file: deploy.yml
      service: tileserver
    ports:
      - "8082:8080"
    volumes:
      - ${DEPLOYMENT_DIRECTORY:-../deployment}:/deployment
      - ${DEPLOYMENT_DIRECTORY:-../deployment}/map:/data/map

  manager:
    extends:
      file: deploy.yml
      service: manager
    image: openremote/manager:${MANAGER_VERSION:-develop}
    build:
      context: ../manager/build/install/manager/
      dockerfile: Dockerfile
    depends_on:
      postgresql:
        condition: service_healthy
      map: # Ensure manager waits for map
        condition: service_started
    volumes:
      - manager-data:/storage
      - ${DEPLOYMENT_DIRECTORY:-../deployment}:/deployment
    environment:
      OR_SETUP_RUN_ON_RESTART: ${OR_SETUP_RUN_ON_RESTART:-true}
      OR_DEV_MODE: ${OR_DEV_MODE:-true}
      OR_HOSTNAME: localhost
      # Set the tileserver host name (matches the service name above)
      OR_MAP_TILESERVER_HOST: map
      # Update port to 8080 (the default for maptiler/tileserver-gl)
      OR_MAP_TILESERVER_PORT: 8080
      OR_MAP_TILESERVER_REQUEST_TIMEOUT: ${OR_MAP_TILESERVER_REQUEST_TIMEOUT:-10000}
      OR_MAP_TILES_PATH: /deployment/map/mapdata.mbtiles
    ports:
      - "8080:8080"
      - "1883:1883"
